In [ ]:
import numpy as np
import pandas as pd
data= pd.read_csv('/content/Golf.csv')
data

    Days   Outlook Temperature Humidity   Windy Play Golf
0      1     Sunny         Hot     High    Weak        No
1      2     Sunny         Hot     High  Strong        No
2      3  Overcast         Hot     High    Weak       Yes
3      4     Rainy        Mild     High    Weak       Yes
4      5     Rainy        Cool   Normal    Weak       Yes
5      6     Rainy        Cool   Normal  Strong        No
6      7  Overcast        Cool   Normal  Strong       Yes
7      8     Sunny        Mild     High    Weak        No
8      9     Sunny        Cool   Normal    Weak       Yes
9     10     Rainy        Mild   Normal    Weak       Yes
10    11     Sunny        Mild   Normal  Strong       Yes
11    12  Overcast        Mild     High  Strong       Yes
12    13  Overcast         Hot   Normal    Weak       Yes
13    14     Rainy        Mild     High  Strong        No

In [ ]:
print(data.shape)

(14, 6)

In [ ]:
 print(data.columns)

Index(['Days', 'Outlook', 'Temperature', 'Humidity', 'Windy', 'Play Golf'], dtype='object')

In [ ]:
 data=data.drop('Days',axis=1)
 data

     Outlook Temperature Humidity   Windy Play Golf
0      Sunny         Hot     High    Weak        No
1      Sunny         Hot     High  Strong        No
2   Overcast         Hot     High    Weak       Yes
3      Rainy        Mild     High    Weak       Yes
4      Rainy        Cool   Normal    Weak       Yes
5      Rainy        Cool   Normal  Strong        No
6   Overcast        Cool   Normal  Strong       Yes
7      Sunny        Mild     High    Weak        No
8      Sunny        Cool   Normal    Weak       Yes
9      Rainy        Mild   Normal    Weak       Yes
10     Sunny        Mild   Normal  Strong       Yes
11  Overcast        Mild     High  Strong       Yes
12  Overcast         Hot   Normal    Weak       Yes
13     Rainy        Mild     High  Strong        No

In [ ]:
 y=data['Play Golf']
 y

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Play Golf, dtype: object

In [ ]:
 x=data.drop('Play Golf',axis=1)
 x

     Outlook Temperature Humidity   Windy
0      Sunny         Hot     High    Weak
1      Sunny         Hot     High  Strong
2   Overcast         Hot     High    Weak
3      Rainy        Mild     High    Weak
4      Rainy        Cool   Normal    Weak
5      Rainy        Cool   Normal  Strong
6   Overcast        Cool   Normal  Strong
7      Sunny        Mild     High    Weak
8      Sunny        Cool   Normal    Weak
9      Rainy        Mild   Normal    Weak
10     Sunny        Mild   Normal  Strong
11  Overcast        Mild     High  Strong
12  Overcast         Hot   Normal    Weak
13     Rainy        Mild     High  Strong

In [ ]:
 from sklearn.preprocessing import LabelEncoder

In [ ]:
 le=LabelEncoder()

In [ ]:
 x.Outlook=le.fit_transform(data['Outlook'])
 x.Temperature=le.fit_transform(data['Temperature'])
 x.Humidity=le.fit_transform(data['Humidity'])
 x.Windy=le.fit_transform(data['Windy'])
 x

    Outlook  Temperature  Humidity  Windy
0         2            1         0      1
1         2            1         0      0
2         0            1         0      1
3         1            2         0      1
4         1            0         1      1
5         1            0         1      0
6         0            0         1      0
7         2            2         0      1
8         2            0         1      1
9         1            2         1      1
10        2            2         1      0
11        0            2         0      0
12        0            1         1      1
13        1            2         0      0

In [ ]:
 from sklearn.model_selection import train_test_split
 x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4, random_state=1)

In [ ]:
 from sklearn.naive_bayes import GaussianNB
 model=GaussianNB()
 model.fit(x,y)
 predicted=model.predict(x_test)
 print("Predicted Value: ", predicted)

Predicted Value:  ['Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes']

In [ ]:
 from sklearn import metrics
 accuracy = metrics.accuracy_score(y_test, predicted)
 print("Accuracy (in %):", accuracy *100 )

Accuracy (in %): 100.0